from .subject_consent_admin import SubjectConsentAdmin
from .subject_death_report_admin import SubjectDeathReportAdmin
from .subject_locator_admin import SubjectLocatorAdmin
from .subject_off_study_admin import SubjectOffStudyAdmin
from .subject_visit_admin import SubjectVisitAdmin
